version: '3.12'

services:
  app:
    build: .
    container_name: crehana_app
    ports:
      - "8001:8000"
    volumes:
      - ./src:/src/src
    depends_on:
      - db
    env_file:
      - .env
    command: >
      /bin/sh -c "
      . .venv/bin/activate && \
      PYTHONPATH=src alembic revision --autogenerate -m 'initial clean migration' && \
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: postgres:13
    container_name: crehana_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
