[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["src/tests"]
python_files = "test_*.py"
addopts = "--cov=src --cov-report=term-missing --cov-fail-under=75"

